name: FTP Push

on:
  push:
    branches: [ gh-pages ]
    
jobs:
  FTP:
    name: Push site to server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: FTP-Upload
      uses: airvzxf/ftp-deployment-action@v1.0-alpha.1
      with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          delete: "false"
          local_dir: ""
          remote_dir: "public_html"
