# This will build the site using Jekyll

name: Jekyll Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: minorDeveloper/jekyll-build-action@v1.4
        
    
    - name: FTP-Upload
      uses: airvzxf/ftp-deployment-action@v1.0-alpha.1
      with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          delete: "false"
          local_dir: "_site"
          remote_dir: "public_html"

