name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret files
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      run: |
        echo $FTP_PASSWORD >> secrets.txt
        echo $FTP_SERVER >> secrets.txt
        echo $FTP_USERNAME >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
